# Generated by Django 2.1 on 2020-05-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='lastname',
        ),
    ]
