# Generated by Django 2.1 on 2020-05-31 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo_app', '0002_auto_20200531_0605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='ContactUs',
        ),
    ]
