# Generated by Django 2.1 on 2020-05-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo_app', '0003_auto_20200531_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
    ]
