# Generated by Django 2.1 on 2020-06-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo_app', '0007_auto_20200601_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbiodata',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
