# Generated by Django 2.1 on 2020-06-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo_app', '0008_auto_20200603_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbiodata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
